import type { Metadata } from "next";
import "../globals.css";
import { Kodchasan, Be_Vietnam_Pro, Fira_Code } from "next/font/google";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/UserContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const fontFira_Code = Fira_Code({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: "400",
});

const kodchasan = Kodchasan({
  variable: "--font-title",
  subsets: ["latin"],
  weight: ["400", "600"],
});

const beVietnam = Be_Vietnam_Pro({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["100", "300", "400", "600"],
});

export const metadata: Metadata = {
  title: "DevCore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${beVietnam.variable} ${kodchasan.variable} ${fontFira_Code.variable}  antialiased`}
      >
        <Toaster
          position="top-center"
          expand
          richColors
          closeButton
          offset={16}
          toastOptions={{
            style: {
              justifyContent: "center",
              gap: 2,
              background: "#cfd6e8",
            },
          }}
        />{" "}
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
