import type { Metadata } from "next";
import "../globals.css";
import { Kodchasan, Be_Vietnam_Pro } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";

const kodchasan = Kodchasan({
  variable: "--font-title",
  subsets: ["latin"],
  weight: ["400", "600"],
});

const beVietnam = Be_Vietnam_Pro({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["100", "300", "400", "600"],
});

export const metadata: Metadata = {
  title: "DevCore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${beVietnam.variable} ${kodchasan.variable} antialiased`}
      >
        <div>
          <Toaster
            position="top-center"
            expand
            richColors
            closeButton
            offset={16}
            toastOptions={{
              style: {
                justifyContent: "center",
                gap: 2,
                background: "#cfd6e8",
              },
            }}
          />
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
